steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lyra-api', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lyra-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - lyra-api
      - --image=gcr.io/$PROJECT_ID/lyra-api
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID
